pub mod bm25;
pub mod chunker;
pub mod citation;
pub mod context_budget;
pub mod document;
pub mod embedding;
pub mod injection;
pub mod merger;
pub mod metadata;
pub mod pipeline;
pub mod retrieval;
pub mod vector_index;

pub use bm25::BM25Retriever;
pub use chunker::{Chunk, ChunkMetadata, StructureAwareChunker};
pub use citation::{Citation, CitationManager};
pub use context_budget::ContextBudget;
pub use document::{detect_content_type, ContentType, Document, DocumentMetadata, Section};
pub use embedding::{cosine_similarity, EmbeddingProvider, LocalEmbeddingProvider};
pub use injection::InjectionDefense;
pub use merger::{Reranker, RetrievalMerger};
pub use metadata::MetadataFilter;
pub use pipeline::{IngestResult, QueryResult, RagPipeline};
pub use retrieval::HybridRetriever;
pub use vector_index::VectorIndex;
